jvm-profiling-tools/honest-profiler

src/main/cpp/agent.cpp, src/main/cpp/globals.h, src/main/cpp/processor.cpp, src/main/cpp/processor.h, src/main/cpp/profiler.cpp, src/main/cpp/profiler.h, src/main/cpp/signal_handler.cpp, src/main/cpp/signal_handler.h, src/test/cpp/test_agent.cpp
In the current code base, there is code to randomize the sampling interval, but it got disabled by 18dbd6c45ffc9d60490fab6b6d4e727af805cfc2.
This PR adds back the functionality, but, by default, uses a fixed sampling interval, with the option of specifying the interval explicitly via a min/max parameter pair.
Also, when the interval is randomized, it changes it every 200 collected samples rather than on every iteration of the processor loop (resetting the timer too often means the actual intervals are never honored, because the timer is reset on the setitimer() call, which is not syncronized with timer expiration).
=> Some changes to the way sampling intervals are specified/used

src/main/java/com/insightfullogic/honest_profiler/core/collector/FlamegraphCollector.java, src/main/java/com/insightfullogic/honest_profiler/core/collector/FlamegraphData.java, src/main/java/com/insightfullogic/honest_profiler/ports/Flamegraph.java
The pull request adds a generic class to aggregate the data (under core.collector) and trivial wrapper that can be used from the command line (under ports, I'm not sure it's the best place).
=> Add a simple collector to generate flame graph data

CMakeLists.txt, src/test/cpp/fixtures.h, src/test/cpp/test.cpp, src/test/cpp/test.h, src/test/cpp/test_agent.cpp, src/test/cpp/test_circular_queue.cpp, src/test/cpp/test_log_writer.cpp
- Eliminates the repetitive `#ifdef __APPLE__` in test files
- Tested building on Ubuntu 14.04 and Mac OS X 10.11.3
=> Add a new header for tests

src/main/cpp/agent.cpp
- Switch to vprintf so varargs passed to logError will be formatted properly
=> Use vprintf for logError

src/main/cpp/agent.cpp, src/main/cpp/globals.h, src/test/cpp/test_agent.cpp
- Switch ConfigurationOptions to use an initializer list instead of the initializeDefaults method
- Safely copy strings, ensuring that they are always NUL-terminated
- If nothing else, there's a bug in the original size calculation where it does `strlen(key)` instead of `strlen(value)`
=> Ensure strings are NUL terminated

src/main/cpp/agent.cpp, src/main/cpp/processor.cpp, src/main/cpp/profiler.cpp, src/main/cpp/profiler.h
- Log additional error cases
- Also prevent `Profiler::start` from creating multiple threads if called repeatedly
- Log messages with an ERROR or WARN prefix. Makes it slightly easier to determine the severity of the message when looking at a log file for stderr
=> Logs and errors

CMakeLists.txt, src/main/cpp/agent.cpp, src/main/cpp/common.cpp, src/main/cpp/common.h, src/main/cpp/controller.cpp, src/main/cpp/controller.h, src/main/cpp/globals.h, src/main/cpp/processor.cpp, src/main/cpp/processor.h, src/main/cpp/profiler.cpp, src/main/cpp/profiler.h
- Enables out-of-process control of the sampling, eliminating the need to include the honest profiler JAR on the classpath of the Java application
- Adds a second agent thread that listens on a socket for control connections
- Control commands are `start`, `stop`, and `status`
- Status command will also print out the log file path
=> Enable sampling to be controlled via a socket

src/test/java/com/insightfullogic/honest_profiler/core/Util.java, src/test/java/com/insightfullogic/honest_profiler/testing_utilities/ProfileFixtures.java, src/test/java/com/insightfullogic/honest_profiler/testing_utilities/VirtualMachineFixtures.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S1118 - “Utility classes should not have public constructors ”.
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1118
Please let me know if you have any questions.
Soso Tughushi
=> fixing squid: S1118 Utility classes should not have public constructors

src/main/java/com/insightfullogic/honest_profiler/core/collector/NodeCollector.java, src/main/java/com/insightfullogic/honest_profiler/core/filters/Filters.java, src/main/java/com/insightfullogic/honest_profiler/ports/console/ConsoleApplication.java, src/main/java/com/insightfullogic/honest_profiler/ports/console/ConsoleLogDumpApplication.java, src/main/java/com/insightfullogic/honest_profiler/ports/javafx/profile/FlatViewModel.java, src/test/java/com/insightfullogic/honest_profiler/system_tests/AgentIntegrationTest.java, src/test/java/com/insightfullogic/honest_profiler/testing_utilities/AgentRunner.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S1213 - The members of an interface declaration or class should appear in a pre-defined order.
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1213
Please let me know if you have any questions.
Soso Tughushi
=> Code quality fix - The members of an interface declaration or class should appear in a pre-defined order

src/main/java/com/insightfullogic/honest_profiler/core/platform/Platforms.java, src/main/java/com/insightfullogic/honest_profiler/ports/sources/LocalMachineSource.java, src/test/java/com/insightfullogic/honest_profiler/ports/console/ConsoleApplicationTest.java, src/test/java/com/insightfullogic/honest_profiler/ports/sources/LocalMachineSourceTest.java, src/test/java/com/insightfullogic/honest_profiler/system_tests/AgentIntegrationTest.java, src/test/java/com/insightfullogic/honest_profiler/testing_utilities/AgentRunner.java
Try build/run honest-profiler on my macbook and had found some problem.
1. That unit test sometimes success, but sometimes failed. It seams that subprocess running InfiniteExample with profile agent that used too much CPU and cause the unit test failed.
So I add agent argument: interval=100 that will decrease the cpu usage and pass the test.
2. The binary's extension for MacOS is dylib, so I create a class named Platforms for some platform specific constant/config.
3. Update some unit test
=> Test enhancement

src/main/java/com/insightfullogic/honest_profiler/ports/javafx/WindowViewModel.java
Without this fix I was seeing this:
```
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Location is not set.
at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2434)
at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
at com.insightfullogic.honest_profiler.ports.javafx.PicoFXLoader.load(PicoFXLoader.java:46)
at com.insightfullogic.honest_profiler.ports.javafx.WindowViewModel.display(WindowViewModel.java:55)
at com.insightfullogic.honest_profiler.ports.javafx.WindowViewModel.displaySta …
```
=> Use case-sensitive name for fxml for Window enum

src/main/cpp/globals.h
The current hard upper limit for `maxFrames` is `512`. That's too low for my use cases. Set the hard limit to `2048`.
=> Set hard limit for maxFrames to 2048

CMakeLists.txt, src/main/cpp/agent.cpp, src/main/cpp/control.cpp, src/main/cpp/controller.cpp, src/main/cpp/controller.h, src/main/cpp/globals.h, src/main/cpp/processor.cpp, src/main/cpp/processor.h, src/main/cpp/profiler.cpp, src/main/cpp/profiler.h, src/main/cpp/trace.h, src/main/java/AgentApiExample.java, src/main/java/com/insightfullogic/honest_profiler/core/control/Agent.java, src/test/cpp/test_profiler_config.cpp, src/test/java/com/insightfullogic/honest_profiler/system_tests/AgentIntegrationTest.java, src/test/java/com/insightfullogic/honest_profiler/testing_utilities/NonInteractiveAgentRunner.java
Hi Richard,
This PR adds getters and setters to Profiler class, so that profiler instance can be configured at runtime via Java (Agent interface) and TCP socket interface (get/set commands). Profiler internally validates all input and frees allocated memory when some data (strings) goes out of the scope. Only **Profiler** specific params can be changed at this moment:
- sampling interval
- max frames to capture
- output file path
I realize that it introduces a lot of changes, but it doesn't break any existing Agent functionality.
=> Add getters and setters to agent's Profiler class

pom.xml
Force locale in the maven-surefire plugin
Fixes #162
=> Java tests fail when default Locale is not 'en'

src/main/cpp/agent.cpp, src/main/cpp/circular_queue.cpp, src/main/cpp/circular_queue.h, src/main/cpp/concurrent_map.h, src/main/cpp/log_writer.cpp, src/main/cpp/log_writer.h, src/main/cpp/processor.cpp, src/main/cpp/profiler.cpp, src/main/cpp/thread_map.h, src/test/cpp/fixtures.h, src/test/cpp/test_log_writer.cpp, src/test/cpp/test_maps.cpp
I've refactored ThreadMap a little to get rid of `thread_local` variables. This is required to support version of clang shipped with XCode to fix #1 issue reported by @eljobe. 
Also reference counting guards were added to `ThreadMap` to prevent heap corruption when `get` and `remove` for the same `JNIenv` happen simultaneously.
=> Remove usage of thread_local variable to support XCode

CMakeLists.txt, src/assembly/zip.xml, src/test/cpp/test.h
Prior to this chnage, there were some incorrect assumptoins about where
the UnitTest++ library was being installed on Mac OS X.
Support for find_package() was added in
unittest-cpp/unittest-cpp@e88121f69e1b4bf36e9d72b129f27ee7b1ed6fdb
This change just uses that newly-added functionality in the
honest-profiler build process on Mac OS X.
After this change, I will also update the wiki with instructions on how
to compile the whole project on Mac OS X.
=> Use find_package() for UnitTest++ no Mac OS X

src/test/cpp/test_profiler_config.cpp
std::ref looks unneeded here, and it causes a compilation error with GCC 6.
=> Compilation fix for (at least) GCC 6

CMakeLists.txt
Otherwise it might pull in unneeded dependencies to X11 libraries.
=> Don't link the agent against the AWT JNI library

src/main/java/com/insightfullogic/honest_profiler/core/aggregation/filter/Comparison.java
The EQUALS_NR Comparison can fail because it checks on Number identity rather than the value.
Trivial, small fix.
As in other current PRs by me - only the last commit in the PR commit list is significant, the other ones amount to no changes.
=> Fix : Comparison "EQUALS_NR" value comparison

src/main/java/com/insightfullogic/honest_profiler/core/aggregation/filter/FilterSpecification.java
Change filter to comply with changes to the naming of "error frames" introduced in #189.
Replaces deleted PR #196 .
=> Fix : #195 Error Filtering

src/main/cpp/concurrent_map.h, src/test/cpp/test.h, src/test/cpp/test_maps.cpp, src/test/cpp/test_misc.cpp, src/test/cpp/test_profiler_config.cpp
Hi,
This PR fixes issue #193 and makes `libagent.so` gcc-4.4 compatible again. I broke compatibility previously when I was developing concurrent map, since non-primitive types appeared in template arguments of `std::atomic` and it doesn't work with `cstdatomic` in g++ 4.4.
Also `nullptr` will be replaced with `NULL` in old gcc's, which is sufficient for honest-profiler (not 100% correct though).
Master passes both java & native tests for both 4.4 and 4.8 under Linux.
=> Fix for issue #193 

src/main/java/com/insightfullogic/honest_profiler/ports/javafx/controller/AbstractProfileDiffViewController.java, src/main/java/com/insightfullogic/honest_profiler/ports/javafx/controller/AbstractProfileViewController.java, src/main/java/com/insightfullogic/honest_profiler/ports/javafx/controller/AbstractViewController.java, src/main/java/com/insightfullogic/honest_profiler/ports/javafx/controller/TreeViewController.java
Fixes a regression, in which certain column headers in diff views no longer show the profile labels.
Replaces part of deleted PR #192 .
=> Fix : Diff column labels missing

src/main/cpp/concurrent_map.h, src/main/cpp/log_writer.cpp, src/main/cpp/log_writer.h, src/main/cpp/profiler.cpp, src/main/java/com/insightfullogic/honest_profiler/core/collector/Frame.java, src/main/java/com/insightfullogic/honest_profiler/core/collector/FullFrame.java, src/main/java/com/insightfullogic/honest_profiler/core/parser/LogParser.java, src/main/java/com/insightfullogic/honest_profiler/core/parser/Method.java, src/main/java/com/insightfullogic/honest_profiler/ports/console/ConsoleLogDumpApplication.java, src/main/java/com/insightfullogic/honest_profiler/ports/console/ProfileFormat.java
This PR adds class signature, method descriptor and method signature to the log. There are not so many changes in agent code since all method calls are already there. I updated Java parser, so it will be able to understand new log entries. Method params and return type (non-generic) will be shown in console applications. `com.insightfullogic.honest_profiler.core.parser.Method` will store class and method signatures but ignore them for now, since pretty printing is a bit more tricky for signatures.
There's a tiny concurrent map change as well (add a copy constructor to map::Migration::Source), that allows agent to be compiled by gcc-4.4.
=> #185: Add method signatures to agent output

src/main/cpp/processor.cpp, src/main/cpp/processor.h
When sampling interval is set to a large value (10's of seconds), VM does not respond to exit and/or Agent.stop() blocks until the sampling duration has elapsed due to Processor sleep'ing.
=> Fix unresponsiveness of agent when sampling duration is large

src/main/cpp/signal_handler.cpp
setSamplingInterval takes milliseconds as parameters for minInterval and maxInterval.
These are used to compute itimer interval; but treated as seconds while registering timer.
=> Use milliseconds for registering itimer

.clang-format, CMakeLists.txt, src/main/cpp/agent.cpp, src/main/cpp/circular_queue.cpp, src/main/cpp/circular_queue.h, src/main/cpp/controller.h, src/main/cpp/log_writer.cpp, src/main/cpp/log_writer.h, src/main/cpp/processor.cpp, src/main/cpp/processor.h, src/main/cpp/profiler.cpp, src/main/cpp/thread_map.cpp, src/main/cpp/thread_map.h, src/test/cpp/fixtures.h, src/test/cpp/test_log_writer.cpp, src/test/cpp/test_profiler_config.cpp, src/test/cpp/test_thread_map.cpp
Hi,
This PR changes `ThreadMap::get` public API (as well as some internal parts of the class), so instead of returning a pointer to internally allocated `ThreadBucket` and managing it's lifecycle directly by calling `release()` method in `LogWriter::record`, the method will return a `ThreadBucketPtr`  wrapper of it. Wrapper will do automatic and atomic reference counting upon construction/destruction and can only be moved. It is moved from signal handler callback to `CircularQueue` and then to `LogWriter`. There's no need to explicitly call any methods (except for std::move in certain cases), once Bucket goes out of scope pointer will be processed correctly. I added a couple of unit tests for thread map as well.
I also did 2 minor changes: 
1. Removed `#ifdef …
=> agent: Protect ThreadBucket* returned from ThreadMap

src/main/cpp/signal_handler.cpp
Proposal for this fix arose from issue #177 and my own personal research. Timer interval registration still seems to be off even after the 302e59d289f36f6ecd170afed5c7b87bd1da6dd7 commit.  
Given that the `timingInterval` is provided in millisecond units, the old version registers the timer with wrong values. Suppose that you set the timing interval with the `interval` flag to `10`. The old version would set the timer's second interval (`it_interval.tv_sec`) to `0` and microsecond value (`it_interval.tv_usec`) to `10`, resulting in a significantly smaller interval as intended (10 microseconds). 
Since the timer registration sets wrong values, it might introduce unexpected results. As issue #177 described, having such a low interval for the itimer configured by ITIMER_REAL limits the …
=> Correct timeunit conversion in timer's registration

CMakeLists.txt
Hello. I've created a fix for that. SSE flags are now included only for x86_64. This should also potentially fix other non-x86 platforms. Checked build on x86_64 and aarch64.
=> #239: No support for Arm64

pom.xml
honest profiler does not, currently, use any of the additional functionality exposed by the higher jackson version.
Unfortuantely, the profiler jackson dependency causes apache spark applications to fail due to version incompatibilities in jackson.
We have been successfully running it in production with the version lowered.
=> Change jackson version to match spark dependency

pom.xml
Maven will run all tests in a single forked VM by default. This can be problematic if there are a lot of tests or some very memory-hungry ones. We can fork more test VM by setting `<fork>1.5C</fork>`.
=====================
If there are any inappropriate modifications in this PR, please give me a reply and I will change them.
=> Run all the tests in multiple forked VM
